runtime: python38

handlers:
# Matches requests to /static/... to files in static/...
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto